on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: |
        git clone https://github.com/Learning-Actions-in-Persian/GA-session1.git
        mv GA-session1/{.,}* .
    
    - name: Install Python and pip
      run: sudo apt-get update && sudo apt-get install -y python3 python3-pip
    
    - name: Install depencies
      run: pip install -r requirements.txt
    
    - name: Run tests
      run: pytest test.py
