on: 
  push:

jobs:
  python-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        run: git clone https://github.com/SeyedMojtaba1/GA-session1.git
      
      - name: Install python and pip
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Insall requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest test.py
