on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "11.3"

      - name: Install depencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest test.py
